### ISSUE TITLE
Extend Eslint 오류 해결

### ISSUE THREAD

**Issue by dayannne** [MusicDigging/Mudig_FE#10]
## 🐛 버그 내용
npm start 실행 후 다음과 같이 에러가 생겨 작동하지 않는 문제가 있었습니다.
먼저 작업하던 서준님에겐 이상이 없던 것 같은데 프로젝트 내 `.eslintrc.js`, `.pagage.json` 설정을 변경해보니 해결되어
제 로컬 문제는 아닌 듯해 설정 추가해 두려 합니다! 

## 📸 스크린샷
<img width="600" alt="스크린샷 2023-11-20 125616" src="https://github.com/MusicDigging/Mudig_FE/assets/105140201/c3584118-542f-40b4-a63b-7e5d7d3b3374">

## 🔍 원인
`.eslintrc.js`, `.pagage.json` 설정에서 발견

## 💡해결방법
- `.eslintrc.js` 에 `parser: '@babel/eslint-parser` 설정 추가
- `package.json`에  `"extends": ["shared-config"]` 설정 추가

**Comment by junny97** [comment]
확인했습니다!
