### ISSUE TITLE
로그인 페이지 리팩토링

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#224]
## 📝 Description
로그인페이지 코드 리팩토링

## 🔨 To-do
- [x]  소셜 로그인 로직 커스텀훅으로 추상화
- [x]  이메일, 회원가입 정규표현식 value 컴포넌트 외부에서 정의로 변경
- [ ]  단일책임
- [ ] 인터페이스 모아두기

## 📌 참고 사항
해당 코드 링크로 연결해서 댓글 달기

**Comment by yejify** [comment]
코드
https://github.com/MusicDigging/Mudig_FE/blob/89170cce876c803101bd1f68fcf9027e8d9410a2/src/pages/Login/Login.tsx#L115C11-L123C13

수정했으면 좋겠는 내용 작성
프롭스가 너무 많은 것 같은데 그럼 컴포넌트로 분리하지 않고 직접 지정해도 괜찮지 않을까?

**Comment by dayannne** [comment]
수정하면 좋을 것 같은 부분 
1. 로그인 페이지 컴포넌트 내 소셜 로그인 부분은 따로 컴포넌트로 분리해도 될 듯
https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/pages/Login/Login.tsx#L17-L27
https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/pages/Login/Login.tsx#L44-L101

2. `components-commpon-Form-AuthForm`은 로그인 페이지에만 사용되는 듯해 `components-Login-AuthForm`과 같이 로그인 페이지 폴더로 들어가는 게 좋지 않을까 싶기도 함 AuthInput도 마찬가지 (물론 개인적인 생각!)

3. AuthInput, SiginupInput 등에 쓰이는 Input을 한 번 더 컴포넌트로 빼는 게 좋을 것 같음
https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/components/common/Input/AuthInput.tsx#L24-L31

4. Regex (정규표현식)따로 모아놓고 가져와 사용하기
https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/components/common/Form/AuthForm.tsx#L18-L19

**Comment by easyxxu** [comment]
**AuthForm.jsx**
- 업데이트되지 않는 값의 경우 외부로 따로 빼기
https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/components/common/Form/AuthForm.tsx#L18-L19
  - 정적인 값의 경우 컴포넌트가 리렌더링될 때마다 같이 재생성됨
따라서, 정적인 값은 이를 방지하기 위해 외부에서 정의
  - (pawwrodRegex -> passwordRegex 오타 수정)
- label 안에 input+label (-> 대신 div 사용)
https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/components/common/Form/AuthForm.tsx#L106-L113

**Comment by junny97** [comment]
꼼꼼한 피드백들 감사합니다. 피드백 바탕으로 리팩토링 진행해볼게요~

**Comment by junny97** [comment]
> 코드
> 
> https://github.com/MusicDigging/Mudig_FE/blob/89170cce876c803101bd1f68fcf9027e8d9410a2/src/pages/Login/Login.tsx#L115-L123
> 
> 수정했으면 좋겠는 내용 작성 프롭스가 너무 많은 것 같은데 그럼 컴포넌트로 분리하지 않고 직접 지정해도 괜찮지 않을까?

기본 버튼 컴포넌트로 구성한 버튼들이랑 똑같은 구조이지만  카카오 버튼, 로그인 버튼에서 추가로 필요한 속성들이 있기 때문에 props로 제어했습니다.

**Comment by junny97** [comment]
> 수정하면 좋을 것 같은 부분
> 
> 1. 로그인 페이지 컴포넌트 내 소셜 로그인 부분은 따로 컴포넌트로 분리해도 될 듯
>    https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/pages/Login/Login.tsx#L17-L27
>    
>    https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/pages/Login/Login.tsx#L44-L101
> 2. `components-commpon-Form-AuthForm`은 로그인 페이지에만 사용되는 듯해 `components-Login-AuthForm`과 같이 로그인 페이지 폴더로 들어가는 게 좋지 않을까 싶기도 함 AuthInput도 마찬가지 (물론 개인적인 생각!)
> 3. AuthInput, SiginupInput 등에 쓰이는 Input을 한 번 더 컴포넌트로 빼는 게 좋을 것 같음
>    https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/components/common/Input/AuthInput.tsx#L24-L31
> 4. Regex (정규표현식)따로 모아놓고 가져와 사용하기
>    https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/components/common/Form/AuthForm.tsx#L18-L19

소셜 로그인 구현 코드는 로그인 페이지 뿐만 아니라 회원가입 페이지에서도 그대로 사용하고 있기에 
useSocialLogin.tsx라는 커스텀훅 파일을 만들고  해당 hook에서 소셜 로그인 로직을 추상화시켰습니다.

**Comment by junny97** [comment]
> **AuthForm.jsx**
> 
> * 업데이트되지 않는 값의 경우 외부로 따로 빼기
>   https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/components/common/Form/AuthForm.tsx#L18-L19
>   
>   
>   * 정적인 값의 경우 컴포넌트가 리렌더링될 때마다 같이 재생성됨
>     따라서, 정적인 값은 이를 방지하기 위해 외부에서 정의
>   * (pawwrodRegex -> passwordRegex 오타 수정)
> * label 안에 input+label (-> 대신 div 사용)
>   https://github.com/MusicDigging/Mudig_FE/blob/c82f19ff9e42de86da26566a7e2f7ea9656d2801/src/components/common/Form/AuthForm.tsx#L106-L113

정적 값 리랜더링 방지 및 label 태그 중복 피드백 반영하여 수정했습니다.
