### ISSUE TITLE
회원가입 페이지 리팩토링

### ISSUE THREAD

**Issue by easyxxu** [MusicDigging/Mudig_FE#227]
## 📝 Description
회원가입 페이지 리팩토링
- [ ]  Signup
- [ ] SignupDetail, SignupForm
- [ ] SetProfile, SetProfileImage, ProfileInput
- [ ] FindPassword
- [ ] ResetPassword
## 🔨 To-do
- [ ] 사용안하는 코드 제거

**Comment by easyxxu** [comment]
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/SetProfile/SetProfile.tsx#L32-L69
- onSubmit가 많은 역할을 하고 있는 것 같다고 생각. onSubmit이 하는 일을 한눈에 이해하기 어렵다고 느낌
- onSubmit 함수에서 필요한 데이터를 추출하는 함수/ onSuccess에서 실행되는 함수 / onError에서 실행되는 함수 분리

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/EditProfile/SetProfileImage.tsx#L57-L65
- 이미지 지원 형식 배열로 담아서 `some` 활용하기
  ```js
   const supportedFormats = ['.jpg', '.png', '.jpeg', '.bmp', '.tif', '.heic'];
   if (!supportedFormats.some(format => file.name.includes(format)))
  ```
(accept 속성으로 이미지 형식 허용하고 있는데 추가로 체크할 필요성이 있는지 궁금했는데 
https://velog.io/@w-hyacinth/%ED%8C%8C%EC%9D%BC-%EC%B2%A8%EB%B6%80-%EC%9E%91%EC%97%85%ED%95%A0-%EB%95%90-accept%EB%A5%BC-%EC%8B%A0%EB%A2%B0%ED%95%98%EC%A7%80-%EB%A7%90%EA%B2%83
해당 글을 통해 accept만 믿고 지원 형식 지정하면 안되겠다고 깨달음)

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/EditProfile/SetProfileImage.tsx#L83
- image/png 오타 수정하기
- image/bmp, image/tiff, image/heic <- 추가로 검사를 하고 있지만 해당 형식도 허용할거면 accept에도 추가해야할 것 같다고 생각

**Comment by yejify** [comment]
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Signup/Signup.tsx#L1
우리 리액트 버전 18.2.0라서 Automatic JSX runtime이 자동으로 되기 때문에 저 구문을 삭제해도 된다고 하는데 어떻게 할까?

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Signup/Signup.tsx#L6-L9
useNavigate빼고 사용 안하는거 같아

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Signup/SignupDetail.tsx#L46-L86
스타일 컴포넌트들은 SignupStyle.jsx파일에서 한번에 관리하는게 좋지 않을까?

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/common/Form/SignupForm.tsx#L35
이거 사용안하는거 같아

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/SetProfile/SetProfile.tsx#L17
이 코드가
`const setUserInfo = useSetRecoilState(userInfoAtom);`
이렇게 변경되면 좋을거 같아
기존 userInfo를 읽지 않고 값을 업데이트만 하니까 리렌더링을 줄여서 성능에 좋을듯

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/FindPassword/FindPasswordForm.tsx#L10
사용안하는거 같아

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/FindPassword/FindPasswordForm.tsx#L25
이것도 사용 안하는거 같아, 위에 import도 같이 삭제하면 될거 같아

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/ResetPassword/ResetPassword.tsx#L20
스타일 컴포넌트 명이 컴포넌트 명이랑 달라서 수정해야 될 거 같아

https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/ResetPassword/ResetPasswordForm.tsx#L21
오타 passwordRegex로 수정해야 될거 같아

**Comment by dayannne** [comment]
- setState만 사용하는 경우 useSetRecoilState로 바꾸면 어떨까?
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Signup/SignupDetail.tsx#L10
` const  setToast = useSetRecoilState(toastAtom);`

- 이것도 정규표현식 따로 분리해 놓은 것 사용하기https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/common/Form/SignupForm.tsx#L16-L17

- 사용 안하는 useEffect 제거
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/common/Form/SignupForm.tsx#L43-L45

- 따로 객체 분해 과정 안거치고 바로 `data.otp` 로 사용해도 될 듯! https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/common/Form/SignupForm.tsx#L59-L61

- style 파일로 한번 분리해도 좋을 듯
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/SetProfile/SetProfile.tsx#L98-L147

- `FindPasswordForm` 과 같은 컴포넌트 파일 components 폴더로 이동하는게 어떨까..? 

- 사용 안하는 요소 제거 (assigned a value but never used)
