### ISSUE TITLE
Intro, Search, RecentSearch, SearchResult 페이지 리팩토링

### ISSUE THREAD

**Issue by yejify** [MusicDigging/Mudig_FE#230]
## 📝 Description
Intro, Search, RecentSearch, SearchResult 페이지 리팩토링

## 🔨 To-do
- [ ]  import 사용 안하는 거삭제
- [ ]  console.log 삭제
- [ ]  style component

## 📌 참고 사항
참고한 블로그 또는 사진 첨부

**Comment by dayannne** [comment]
- Intro 페이지 컴포넌트 스타일 분리하기
- color props로 전달하지 않고 스타일 컴포넌트에서 바로 지정하기 https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/Intro.tsx#L35
- 버튼에 onClick 이벤트 기능들이 없다....? 로그인 처리를 안하고 있던 건가요,,,?
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/Intro.tsx#L25-L32
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Home/Intro.tsx#L37
   아래 기능 추가할 것
  ```
    const kakaoLoginHandler = useSocialLogin(getKakaoInfo, 'kakao');
    const googleLoginHandler = useSocialLogin(getGoogleInfo, 'google');
  ```
- prevState 사용하기
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Search/SearchResult.tsx#L29-L42
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/Search/SearchNav.tsx#L10-L18
  ```tsx
  setCurrentNav((prev)=>({ ...prev, playlist: true }));
  ```
- 중복되는 EmptySearch 처리하는 부분 분리해 로직을 따로 만들어보면 어떨까?

  GPT에게 부탁한 예시)
  ```tsx
  export default function SearchResultAll(props) {
    const {
      result,
      handleAddPlaylist,
      handleNavPlaylist,
      handleNavMusic,
      handleNavUser,
    } = props;
  
    // 각 섹션별 렌더링 로직을 처리하는 컴포넌트
    const renderSection = (title, handleNav, ariaLabel, data, renderItem) => (
      <SearchListSection>
        <SearchResultTitle title={title} handleNav={handleNav} ariaLabel={ariaLabel} />
        <ul>
          {data.length !== 0 ? (
            data.map(renderItem)
          ) : (
            <EmptySearch />
          )}
        </ul>
      </SearchListSection>
    );
  
    return (
      <>
        <SearchListBox>
          {renderSection(
            '플리 검색결과',
            handleNavPlaylist,
            '플레이리스트 검색결과 더보기',
            result.recent_playlists,
            (item) => (
              <li key={item.playlist.id}>
                <Link to={`/playlist/detail/${item.playlist.id}`} state={{ id: item.playlist.id }}>
                  <PlayListItem
                    img={item.playlist.thumbnail}
                    title={item.playlist.title}
                    info={
                      typeof item.writer === 'string' && item.writer === '유저 정보 없음'
                        ? '알 수 없는 사용자'
                        : item.writer.name
                    }
                  />
                </Link>
              </li>
            )
          )}
          {renderSection(
            '노래 검색결과',
            handleNavMusic,
            '노래 검색결과 더보기',
            result.search_music[0] ? result.search_music[0].music.slice(0, 3) : [],
            (item) => (
              <PlayListItem
                key={item.id}
                img={item.thumbnail}
                title={item.song}
                info={item.singer}
              >
                <button type="button" onClick={() => handleAddPlaylist(item.id)}>
                  <img src={AddPlaylist} alt="플레이리스트에추가" />
                </button>
              </PlayListItem>
            )
          )}
          {renderSection(
            '유저 검색결과',
            handleNavUser,
            '유저 검색결과 더보기',
            result.recent_users,
            (user) => (
              <li key={user.id}>
                <Link to={`/user/profile/${user.id}`} state={{ id: user.id }}>
                  <UserItem>
                    <UserImgBox>
                      <CircleImage src={user.image} alt="유저이미지" />
                    </UserImgBox>
                    <UserInfoBox>
                      <div>{user.name}</div>
                      <p>{user.about}</p>
                    </UserInfoBox>
                  </UserItem>
                </Link>
              </li>
            )
          )}
        </SearchListBox>
      </>
    );
  }
  
  ```

**Comment by junny97** [comment]
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Search/SearchResult.tsx#L17-L22

객체 값 조정을 state 대신 useReducer로 관리하는 것도 괜찮아보여
예시
```js
interface INavState {
  all: boolean;
  playlist: boolean;
  music: boolean;
  user: boolean;
}

type NavAction = { type: 'SET_NAV'; payload: keyof NavState }; 

const initialState: INavState = {
  all: true,
  playlist: false,
  music: false,
  user: false,
};

//Reducer 함수 
  function navReducer(state: NavState, action: NavAction): NavState {
    switch (action.type) {
      case 'SET_NAV':
        return {
          ...initialState,
          [action.payload]: true,
        };
      default:
        return state;
    }
  }
  
  export default function SearchResult() {
    const [currentNav, dispatch] = useReducer(navReducer, initialState);

  useEffect(() => {
    refetch();
    dispatch({ type: 'SET_NAV', payload: 'all' });
  }, [keyword]);
}
    <SearchResultAll
            result={result}
            handleAddPlaylist={handleAddPlaylist}
            handleNavPlaylist={() => dispatch({ type: 'SET_NAV', payload: 'playlist' })}
            handleNavMusic={() => dispatch({ type: 'SET_NAV', payload: 'music' })}
            handleNavUser={() => dispatch({ type: 'SET_NAV', payload: 'user' })}
          />

```

**Comment by yejify** [comment]
코드가 중복되는 부분이 있는거 같아
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Search/Search.tsx#L22-L42
검색하는 키워드를 제외하고 목록을 구성한 뒤 현재 키워드를 위에 올리면 되지 않을까?
`const handleAddRecentKeyword = (keyword: string) => {
    // 현재 검색어를 제외한 나머지 검색어들로 구성된 새 목록을 생성
    const updatedKeywords = recentKeywords.filter(
        (item: IStoredKeyword) => item.keyword !== keyword,
    );

    const newKeyword = {
        id: Date.now(),
        keyword,
    };

    // 새로운 검색어를 목록의 맨 앞에 추가
    setRecentKeywords([newKeyword, ...updatedKeywords]);
};
`

**Comment by yejify** [comment]
useEffect가 매 상태 업데이트마다 로컬 스토리지에 접근해서, 성능에 영향을 줄 수 있을거 같아.
https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Search/Search.tsx#L54-L57

실제로 변경사항이 있을 때만 로컬스토리지에 접근하도록 코드를 바꾸는 건 어떨까?
```
useEffect(() => {
  const storedKeywords = JSON.parse(localStorage.getItem('recent_keywords') || '[]');
  if (JSON.stringify(storedKeywords) !== JSON.stringify(recentKeywords)) {
    localStorage.setItem('recent_keywords', JSON.stringify(recentKeywords));
  }
}, [recentKeywords]);

```

**Comment by easyxxu** [comment]
> * prevState 사용하기
>   https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/pages/Search/SearchResult.tsx#L29-L42
>   
>   https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/Search/SearchNav.tsx#L10-L18
>   
>   ```tsx
>   setCurrentNav((prev)=>({ ...prev, playlist: true }));
>   ```

- SearchResult 컴포넌트에서는 prev를 이용할 수 있도록 수정
- SearchNav 컴포넌트는 현재 nav가 어디냐에 따라 영향을 줘서 prev 적용 X
---
> * 중복되는 EmptySearch 부분 분리해 로직을 따로 만들어보면 어떨까?
>   https://github.com/MusicDigging/Mudig_FE/blob/b81978c436816f39a0264cb0e8a27c65c1b18595/src/components/Search/SearchResultAll.tsx#L18-L130

-> Compound Component Pattern을 활용하여 EmptySearch 중복 개선
