### ISSUE TITLE
비밀번호 보기/ 숨기기 기능 버그 해결 

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#28]
## 🐛 버그 내용
유저가 선택한 해당 필드의 비밀번호만 보이기/숨기기를 수행해야 되는데 비밀번호 보기/숨기기 버튼 클릭시 해당 필드와 관련 없는 나머지 비밀번호 필드의 값들까지  같이 동작하는 문제가 발생했습니다.
## 📸 스크린샷
![errorpw](https://github.com/MusicDigging/Mudig_FE/assets/72855681/a1cf0094-d837-455e-a1ba-65ffbdf1a4f0)
 

## 🔍 원인
```js
//usePasswordToggle hook
const usePasswordToggle = () => {
  const [showPassword, setShowPassword] = useState(false); 

  const toggleShowPassword = () => {
    setShowPassword((prevValue) => !prevValue);
  };

  return { toggleShowPassword, showPassword };
};

export default usePasswordToggle;
```

```js
 //Input 컴포넌트 
    <Input //props로 type을 전달해주어 비밀번호 보기 버튼을 클릭했을때 true라면 pasword 타입을 text로 변경하여 보이게 하는 형식
          type={showPassword ? 'text' : type}
        />
// Input 컴포넌트 props 적용 
 <SignupInput
            type='password'
            showPassword={showPassword}
            toggleShowPassword={toggleShowPassword}
          />
```
비밀번호/새 비밀번호, 비밀번호 확인 3개의 input 모두 input type='password'로 설정되어 있었고, showPassword 상태 변경을 
단순히 true/false로만 관리하고 있어, 클릭 한 번으로 모든 비밀번호가 보이거나 숨겨지는 문제가 발생했습니다.

## 💡해결방법
```js
//usePasswordToggle hook
const usePasswordToggle = () => {
  const [showPassword, setShowPassword] = useState({}); // 객체로 변경 

  const toggleShowPassword = (name) => {
    setShowPassword((prev) => ({
      ...prev,
      [name]: !prev[name], //해당 key값의 true/false만 변경
    }));
  };

  return { toggleShowPassword, showPassword };
};
```

```js
 //Input 컴포넌트 
    <Input
          type={showPassword ? 'text' : type}
        />
// Input 컴포넌트 props 적용 
 <SignupInput
             type='password'
            showPassword={showPassword.confirmPassword}
            toggleShowPassword={() => toggleShowPassword('confirmPassword')}
          />

```

먼저, boolean 타입에서 객체로 상태를 변경했습니다. toggleShowPassword 함수에 name을 매개변수로 전달하여 </br> toggleShowPassword={() => toggleShowPassword('confirmPassword')} 콜백 함수 실행 시 지정된 name을 전달합니다.
그리고 전달된 name을 객체로 설정한 showPassword.name으로 바인딩하여 상태를 업데이트합니다.
위 방식을 통해 전달된 name을 key값으로 사용하여 해당 key값을 가진 필드만 비밀번호 보이기/숨기기 기능이 실행되어 모든 password가 반응하여 비밀번호가 보여지는 것을 방지했습니다.
</br>
![fixpwerr](https://github.com/MusicDigging/Mudig_FE/assets/72855681/202c34ff-d2f6-476c-beba-4f9ce8d871f6)

## 📌 참고 사항
참고한 블로그 또는 사진 첨부

**Comment by yejify** [comment]
서준님 비밀번호 확인은 원래 안보이게 하지 않나요..?

**Comment by junny97** [comment]
일단 디자인엔 있어서 작업했는데 생각해보니 다른 사이트들에선 비밀번호 확인은 못 보게 했던거 같네요 그럼 일단 안보이는 버전도 만들어 볼게요
