### ISSUE TITLE
인트로 페이지 구현

### ISSUE THREAD

**Issue by junny97** [MusicDigging/Mudig_FE#38]
## 📝 Description
로그인 하지 않은 상태에서 접근하는 인트로 페이지 UI를 구현합니다 

## 🔨 To-do
- [x]  로그인 하지 않은 상태에서 접근하는  인트로 페이지 UI 구현

## 📌 참고 사항

![메인 - (로그인 하지 않은 상태로, 콘텐츠 클릭했을 때)](https://github.com/MusicDigging/Mudig_FE/assets/72855681/e9a2ca9a-89cd-446f-8035-5e624bb15669)

**Comment by yejify** [comment]
서준님 그거 누가 할지 안정해서 제가 하려고 했는데
해주셔서 감사해요ㅎㅎㅎ

**Comment by dayannne** [comment]
저두 안정해져서 제가 만드려 했는데 감사함니다ㅎㅎ
